apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
          - /bin/sh
          - -c
          - |
            bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      containers:
      - name: frontend-echo-symphony
        image: appnetorg/echo-symphony:latest
        command: ["/app/frontend/frontend"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command: ["/app/proxy"]
        securityContext:
          runAsUser: 1337
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  clusterIP: None
  ports:
  - name: server
    port: 11000
    protocol: UDP
    targetPort: 11000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
          - /bin/sh
          - -c
          - |
            bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      containers:
      - image: appnetorg/echo-symphony:latest
        name: server-echo-symphony
        command: ["/app/server/server"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command: ["/app/proxy"]
        securityContext:
          runAsUser: 1337
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]