// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package money

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Money struct {
	_tab flatbuffers.Table
}

func GetRootAsMoney(buf []byte, offset flatbuffers.UOffsetT) *Money {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Money{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Money) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Money) Table() flatbuffers.Table {
	return rcv._tab
}

// The 3-letter currency code defined in ISO 4217.
func (rcv *Money) CurrencyCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// The whole units of the amount.
// For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.
func (rcv *Money) Units() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Money) MutateUnits(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

// Number of nano (10^-9) units of the amount.
// The value must be between -999,999,999 and +999,999,999 inclusive.
// If `units` is positive, `nanos` must be positive or zero.
// If `units` is zero, `nanos` can be positive, zero, or negative.
// If `units` is negative, `nanos` must be negative or zero.
// For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.
func (rcv *Money) Nanos() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Money) MutateNanos(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func MoneyStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MoneyAddCurrencyCode(builder *flatbuffers.Builder, currencyCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(currencyCode), 0)
}
func MoneyAddUnits(builder *flatbuffers.Builder, units int64) {
	builder.PrependInt64Slot(1, units, 0)
}
func MoneyAddNanos(builder *flatbuffers.Builder, nanos int32) {
	builder.PrependInt32Slot(2, nanos, 0)
}
func MoneyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}

