#!/bin/bash
set -euo pipefail

export NIC_QUEUES=${NIC_QUEUES:-4}
export APP_THREADS=${APP_THREADS:-4}
export KV_CONNECTIONS=${KV_CONNECTIONS:-64}
export PENDING_MESSAGES=${PENDING_MESSAGES:-64}
export KEY_COUNT=${KEY_COUNT:-1000}
export VALUE_SIZE=${VALUE_SIZE:-64}
export TARGET_MOPS=${TARGET_MOPS:-0.9}
export MICROKERNEL_EXTRA_ARGS=${MICROKERNEL_EXTRA_ARGS:--n}
export SERVER_EPOLL_TIMEOUT_MS=${SERVER_EPOLL_TIMEOUT_MS:-10}
export REQUEST_GAP_NS=0
export WARMUP_SECONDS=${WARMUP_SECONDS:-2}
export RUN_SECONDS=${RUN_SECONDS:-30}
export COOLDOWN_SECONDS=${COOLDOWN_SECONDS:-1}

exec "$(dirname "$0")/run_arpc_kv_cases.sh"
