// Code generated by capnpc-go. DO NOT EDIT.

package echo_capnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
	math "math"
)

type EchoRequest capnp.Struct

// EchoRequest_TypeID is the unique identifier for the type EchoRequest.
const EchoRequest_TypeID = 0xc1220377c3a1b7a0

func NewEchoRequest(s *capnp.Segment) (EchoRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoRequest(st), err
}

func NewRootEchoRequest(s *capnp.Segment) (EchoRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoRequest(st), err
}

func ReadRootEchoRequest(msg *capnp.Message) (EchoRequest, error) {
	root, err := msg.Root()
	return EchoRequest(root.Struct()), err
}

func (s EchoRequest) String() string {
	str, _ := text.Marshal(0xc1220377c3a1b7a0, capnp.Struct(s))
	return str
}

func (s EchoRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoRequest) DecodeFromPtr(p capnp.Ptr) EchoRequest {
	return EchoRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoRequest) Id() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s EchoRequest) SetId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s EchoRequest) Score() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s EchoRequest) SetScore(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s EchoRequest) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EchoRequest) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoRequest) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EchoRequest) SetContent(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EchoRequest) Tag() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s EchoRequest) HasTag() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s EchoRequest) TagBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s EchoRequest) SetTag(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// EchoRequest_List is a list of EchoRequest.
type EchoRequest_List = capnp.StructList[EchoRequest]

// NewEchoRequest creates a new list of EchoRequest.
func NewEchoRequest_List(s *capnp.Segment, sz int32) (EchoRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[EchoRequest](l), err
}

// EchoRequest_Future is a wrapper for a EchoRequest promised by a client call.
type EchoRequest_Future struct{ *capnp.Future }

func (f EchoRequest_Future) Struct() (EchoRequest, error) {
	p, err := f.Future.Ptr()
	return EchoRequest(p.Struct()), err
}

type EchoResponse capnp.Struct

// EchoResponse_TypeID is the unique identifier for the type EchoResponse.
const EchoResponse_TypeID = 0xb798c2c3642ab860

func NewEchoResponse(s *capnp.Segment) (EchoResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoResponse(st), err
}

func NewRootEchoResponse(s *capnp.Segment) (EchoResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoResponse(st), err
}

func ReadRootEchoResponse(msg *capnp.Message) (EchoResponse, error) {
	root, err := msg.Root()
	return EchoResponse(root.Struct()), err
}

func (s EchoResponse) String() string {
	str, _ := text.Marshal(0xb798c2c3642ab860, capnp.Struct(s))
	return str
}

func (s EchoResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoResponse) DecodeFromPtr(p capnp.Ptr) EchoResponse {
	return EchoResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoResponse) Id() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s EchoResponse) SetId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s EchoResponse) Score() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s EchoResponse) SetScore(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s EchoResponse) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EchoResponse) HasContent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoResponse) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EchoResponse) SetContent(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EchoResponse) Tag() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s EchoResponse) HasTag() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s EchoResponse) TagBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s EchoResponse) SetTag(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// EchoResponse_List is a list of EchoResponse.
type EchoResponse_List = capnp.StructList[EchoResponse]

// NewEchoResponse creates a new list of EchoResponse.
func NewEchoResponse_List(s *capnp.Segment, sz int32) (EchoResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[EchoResponse](l), err
}

// EchoResponse_Future is a wrapper for a EchoResponse promised by a client call.
type EchoResponse_Future struct{ *capnp.Future }

func (f EchoResponse_Future) Struct() (EchoResponse, error) {
	p, err := f.Future.Ptr()
	return EchoResponse(p.Struct()), err
}

type EchoService capnp.Client

// EchoService_TypeID is the unique identifier for the type EchoService.
const EchoService_TypeID = 0xe8f0ccf9e3e40d00

func (c EchoService) Echo(ctx context.Context, params func(EchoService_echo_Params) error) (EchoService_echo_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe8f0ccf9e3e40d00,
			MethodID:      0,
			InterfaceName: "echo.capnp:EchoService",
			MethodName:    "echo",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EchoService_echo_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EchoService_echo_Results_Future{Future: ans.Future()}, release

}

func (c EchoService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c EchoService) String() string {
	return "EchoService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c EchoService) AddRef() EchoService {
	return EchoService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c EchoService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c EchoService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c EchoService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (EchoService) DecodeFromPtr(p capnp.Ptr) EchoService {
	return EchoService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c EchoService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c EchoService) IsSame(other EchoService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c EchoService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c EchoService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A EchoService_Server is a EchoService with a local implementation.
type EchoService_Server interface {
	Echo(context.Context, EchoService_echo) error
}

// EchoService_NewServer creates a new Server from an implementation of EchoService_Server.
func EchoService_NewServer(s EchoService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(EchoService_Methods(nil, s), s, c)
}

// EchoService_ServerToClient creates a new Client from an implementation of EchoService_Server.
// The caller is responsible for calling Release on the returned Client.
func EchoService_ServerToClient(s EchoService_Server) EchoService {
	return EchoService(capnp.NewClient(EchoService_NewServer(s)))
}

// EchoService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func EchoService_Methods(methods []server.Method, s EchoService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe8f0ccf9e3e40d00,
			MethodID:      0,
			InterfaceName: "echo.capnp:EchoService",
			MethodName:    "echo",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Echo(ctx, EchoService_echo{call})
		},
	})

	return methods
}

// EchoService_echo holds the state for a server call to EchoService.echo.
// See server.Call for documentation.
type EchoService_echo struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EchoService_echo) Args() EchoService_echo_Params {
	return EchoService_echo_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EchoService_echo) AllocResults() (EchoService_echo_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Results(r), err
}

// EchoService_List is a list of EchoService.
type EchoService_List = capnp.CapList[EchoService]

// NewEchoService_List creates a new list of EchoService.
func NewEchoService_List(s *capnp.Segment, sz int32) (EchoService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[EchoService](l), err
}

type EchoService_echo_Params capnp.Struct

// EchoService_echo_Params_TypeID is the unique identifier for the type EchoService_echo_Params.
const EchoService_echo_Params_TypeID = 0xd852f6756d123ece

func NewEchoService_echo_Params(s *capnp.Segment) (EchoService_echo_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Params(st), err
}

func NewRootEchoService_echo_Params(s *capnp.Segment) (EchoService_echo_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Params(st), err
}

func ReadRootEchoService_echo_Params(msg *capnp.Message) (EchoService_echo_Params, error) {
	root, err := msg.Root()
	return EchoService_echo_Params(root.Struct()), err
}

func (s EchoService_echo_Params) String() string {
	str, _ := text.Marshal(0xd852f6756d123ece, capnp.Struct(s))
	return str
}

func (s EchoService_echo_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoService_echo_Params) DecodeFromPtr(p capnp.Ptr) EchoService_echo_Params {
	return EchoService_echo_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoService_echo_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoService_echo_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoService_echo_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoService_echo_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoService_echo_Params) Req() (EchoRequest, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EchoRequest(p.Struct()), err
}

func (s EchoService_echo_Params) HasReq() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoService_echo_Params) SetReq(v EchoRequest) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewReq sets the req field to a newly
// allocated EchoRequest struct, preferring placement in s's segment.
func (s EchoService_echo_Params) NewReq() (EchoRequest, error) {
	ss, err := NewEchoRequest(capnp.Struct(s).Segment())
	if err != nil {
		return EchoRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// EchoService_echo_Params_List is a list of EchoService_echo_Params.
type EchoService_echo_Params_List = capnp.StructList[EchoService_echo_Params]

// NewEchoService_echo_Params creates a new list of EchoService_echo_Params.
func NewEchoService_echo_Params_List(s *capnp.Segment, sz int32) (EchoService_echo_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[EchoService_echo_Params](l), err
}

// EchoService_echo_Params_Future is a wrapper for a EchoService_echo_Params promised by a client call.
type EchoService_echo_Params_Future struct{ *capnp.Future }

func (f EchoService_echo_Params_Future) Struct() (EchoService_echo_Params, error) {
	p, err := f.Future.Ptr()
	return EchoService_echo_Params(p.Struct()), err
}
func (p EchoService_echo_Params_Future) Req() EchoRequest_Future {
	return EchoRequest_Future{Future: p.Future.Field(0, nil)}
}

type EchoService_echo_Results capnp.Struct

// EchoService_echo_Results_TypeID is the unique identifier for the type EchoService_echo_Results.
const EchoService_echo_Results_TypeID = 0xf47bc8e9b85ec174

func NewEchoService_echo_Results(s *capnp.Segment) (EchoService_echo_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Results(st), err
}

func NewRootEchoService_echo_Results(s *capnp.Segment) (EchoService_echo_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Results(st), err
}

func ReadRootEchoService_echo_Results(msg *capnp.Message) (EchoService_echo_Results, error) {
	root, err := msg.Root()
	return EchoService_echo_Results(root.Struct()), err
}

func (s EchoService_echo_Results) String() string {
	str, _ := text.Marshal(0xf47bc8e9b85ec174, capnp.Struct(s))
	return str
}

func (s EchoService_echo_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoService_echo_Results) DecodeFromPtr(p capnp.Ptr) EchoService_echo_Results {
	return EchoService_echo_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoService_echo_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoService_echo_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoService_echo_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoService_echo_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoService_echo_Results) Resp() (EchoResponse, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EchoResponse(p.Struct()), err
}

func (s EchoService_echo_Results) HasResp() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoService_echo_Results) SetResp(v EchoResponse) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResp sets the resp field to a newly
// allocated EchoResponse struct, preferring placement in s's segment.
func (s EchoService_echo_Results) NewResp() (EchoResponse, error) {
	ss, err := NewEchoResponse(capnp.Struct(s).Segment())
	if err != nil {
		return EchoResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// EchoService_echo_Results_List is a list of EchoService_echo_Results.
type EchoService_echo_Results_List = capnp.StructList[EchoService_echo_Results]

// NewEchoService_echo_Results creates a new list of EchoService_echo_Results.
func NewEchoService_echo_Results_List(s *capnp.Segment, sz int32) (EchoService_echo_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[EchoService_echo_Results](l), err
}

// EchoService_echo_Results_Future is a wrapper for a EchoService_echo_Results promised by a client call.
type EchoService_echo_Results_Future struct{ *capnp.Future }

func (f EchoService_echo_Results_Future) Struct() (EchoService_echo_Results, error) {
	p, err := f.Future.Ptr()
	return EchoService_echo_Results(p.Struct()), err
}
func (p EchoService_echo_Results_Future) Resp() EchoResponse_Future {
	return EchoResponse_Future{Future: p.Future.Field(0, nil)}
}

const schema_bf5147bb3b06fa3d = "x\xda\xcc\x92Ok\x13Q\x14\xc5\xcfyw\xa6#m" +
	"C\xf3\x9c\x80\xd0M!\xb4\x9b@\x8b\x7fv\x8a\xa6\x08" +
	"\xd2U!/\xa5;\x91\x0e\x93\x87\x094\x99\xe9\xccD" +
	")\"~\x0d\x97\xfa)Z\xeaB\xdan\\\x88k\xf7" +
	"\x0a\xea\xce\x85\x08\xbap\xe4\xb5&Q\x08\xb8\xed\xeep" +
	"\xb9\xf3\x9b\xdf\xe5\x9d\xab+\\\xf7\xaeU\x96\x04\xca," +
	"\xfb3\xe5\xcea\xa3sz\xf2\xfc\x00f\x8e,o\xff" +
	"\x9c\xb9\xf5j\xc3\xbc\x86\xaf\x02 \x1c\xf2$|J\x97" +
	"\xf6\xf9\x09,_\x1c\xbc<},\xf5\xe3\xa9\xcb\x9b\xea" +
	"(\xdc>KF\xb9\xe5ww.\xf7\x87\xdf\xdb\xef\xa1" +
	"\xaf\x10\xf0\x1d\xe6\xc6\x8a,\x12\x0cW\xa5\x09\xfe\xaa|" +
	"\xfc\xf0\xe3\xed\xd7\xcfzN&(0\xdc\x94\xa3p[" +
	"\xce8\xb2\x11\xee\xbbT\x16\xc7\x0f\x0e\xbf\xbcy\xf2\xed" +
	"oV$u\xc7\xeaI\x13\xab\xa5\x8d\xbb\xc9Z\x1c\xa5" +
	"j\x90\xde\xbc\x17w\x93\xb6\xcd\xd3d\x90[\xb4HS" +
	"\x15\x0f\xf0\x08\xe8h\x110\xf7\x85\xa6\xab\xa8\xc9\x1a\xdd" +
	"\xd0^\x07\xcc\x8e\xd0\xec*R\xd5\xa8\x00\xdd\xbb\x0b\x98" +
	"\x8e\xd0\xa4\x8aZX\xa3\x00\xba_\x07LWh\x0aE" +
	"\xe9u\xe8A\xd1\x03\x97\xf28\xc9,g\xa18\x0b>" +
	"\x8b\x93Aa\x07\x05\xe7\xa18\x0f\x06E\xf4p\x94\xc7" +
	"\x9a\x1ci6\xed\xde\xd0\xe6\xc5\xc5\xb4\x94?\x96[6" +
	"{\xd4\x8b\xed\x9a\x9b/\xb7\xa2,\x92~n\xbc\xb1n" +
	"\xc5\xfd\xf0\x92\xd0\xd4\x14\x83\xcc\xee\xb1:)\x0a\xc8\xea" +
	"\x94\xbb\xb7\x9a\xe7Hw\xb7'>0n\x0bGO\xad" +
	"u\x03J\xfb\xc1\x82\xfbv\x9d-\xfe\xc7\xabm\xf3a" +
	"\xb0[\xfc#\xd6\x98\x88-d6OY\x9d\xf4\xfd\xdc" +
	"\xecw\x00\x00\x00\xff\xff\x13\xaf\xb4R"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_bf5147bb3b06fa3d,
		Nodes: []uint64{
			0xb798c2c3642ab860,
			0xc1220377c3a1b7a0,
			0xd852f6756d123ece,
			0xe8f0ccf9e3e40d00,
			0xf47bc8e9b85ec174,
		},
		Compressed: true,
	})
}
