// Code generated by protoc-gen-arpc. DO NOT EDIT.
package echo

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
	"github.com/appnet-org/arpc/pkg/rpc/element"
)

// Service IDs
const (
	ServiceID_EchoService = 1
)

// Service name <-> ID mappings
var serviceNameToID = map[string]uint32{
	"EchoService": ServiceID_EchoService,
}

var serviceIDToName = map[uint32]string{
	ServiceID_EchoService: "EchoService",
}

// Method IDs for EchoService
const (
	EchoService_MethodID_Echo = 1
)

// Method name <-> ID mappings for EchoService
var EchoService_methodNameToID = map[string]uint32{
	"Echo": EchoService_MethodID_Echo,
}

var EchoService_methodIDToName = map[uint32]string{
	EchoService_MethodID_Echo: "Echo",
}

// EchoServiceClient is the client API for EchoService service.
type EchoServiceClient interface {
	Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error)
}

type arpcEchoServiceClient struct {
	client *rpc.Client
}

func NewEchoServiceClient(client *rpc.Client) EchoServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("EchoService", ServiceID_EchoService, EchoService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcEchoServiceClient{client: client}
}

func (c *arpcEchoServiceClient) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	resp := new(EchoResponse)
	if err := c.client.Call(ctx, "EchoService", "Echo", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type EchoServiceServer interface {
	Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, context.Context, error)
}

func RegisterEchoServiceServer(s *rpc.Server, srv EchoServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "EchoService",
		ServiceID:   ServiceID_EchoService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			EchoService_MethodID_Echo: {
				MethodName: "Echo",
				MethodID:   EchoService_MethodID_Echo,
				Handler:    _EchoService_Echo_Handler,
			},
		},
	}, srv)
}

func _EchoService_Echo_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(EchoRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(EchoServiceServer).Echo(ctx, req.Payload.(*EchoRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}
