// Code generated by capnpc-go. DO NOT EDIT.

package echo_capnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type EchoService capnp.Client

// EchoService_TypeID is the unique identifier for the type EchoService.
const EchoService_TypeID = 0xe8f0ccf9e3e40d00

func (c EchoService) Echo(ctx context.Context, params func(EchoService_echo_Params) error) (EchoService_echo_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe8f0ccf9e3e40d00,
			MethodID:      0,
			InterfaceName: "echo.capnp:EchoService",
			MethodName:    "echo",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(EchoService_echo_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return EchoService_echo_Results_Future{Future: ans.Future()}, release

}

func (c EchoService) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c EchoService) String() string {
	return "EchoService(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c EchoService) AddRef() EchoService {
	return EchoService(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c EchoService) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c EchoService) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c EchoService) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (EchoService) DecodeFromPtr(p capnp.Ptr) EchoService {
	return EchoService(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c EchoService) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c EchoService) IsSame(other EchoService) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c EchoService) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c EchoService) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A EchoService_Server is a EchoService with a local implementation.
type EchoService_Server interface {
	Echo(context.Context, EchoService_echo) error
}

// EchoService_NewServer creates a new Server from an implementation of EchoService_Server.
func EchoService_NewServer(s EchoService_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(EchoService_Methods(nil, s), s, c)
}

// EchoService_ServerToClient creates a new Client from an implementation of EchoService_Server.
// The caller is responsible for calling Release on the returned Client.
func EchoService_ServerToClient(s EchoService_Server) EchoService {
	return EchoService(capnp.NewClient(EchoService_NewServer(s)))
}

// EchoService_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func EchoService_Methods(methods []server.Method, s EchoService_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 1)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe8f0ccf9e3e40d00,
			MethodID:      0,
			InterfaceName: "echo.capnp:EchoService",
			MethodName:    "echo",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Echo(ctx, EchoService_echo{call})
		},
	})

	return methods
}

// EchoService_echo holds the state for a server call to EchoService.echo.
// See server.Call for documentation.
type EchoService_echo struct {
	*server.Call
}

// Args returns the call's arguments.
func (c EchoService_echo) Args() EchoService_echo_Params {
	return EchoService_echo_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c EchoService_echo) AllocResults() (EchoService_echo_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Results(r), err
}

// EchoService_List is a list of EchoService.
type EchoService_List = capnp.CapList[EchoService]

// NewEchoService_List creates a new list of EchoService.
func NewEchoService_List(s *capnp.Segment, sz int32) (EchoService_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[EchoService](l), err
}

type EchoService_echo_Params capnp.Struct

// EchoService_echo_Params_TypeID is the unique identifier for the type EchoService_echo_Params.
const EchoService_echo_Params_TypeID = 0xd852f6756d123ece

func NewEchoService_echo_Params(s *capnp.Segment) (EchoService_echo_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Params(st), err
}

func NewRootEchoService_echo_Params(s *capnp.Segment) (EchoService_echo_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Params(st), err
}

func ReadRootEchoService_echo_Params(msg *capnp.Message) (EchoService_echo_Params, error) {
	root, err := msg.Root()
	return EchoService_echo_Params(root.Struct()), err
}

func (s EchoService_echo_Params) String() string {
	str, _ := text.Marshal(0xd852f6756d123ece, capnp.Struct(s))
	return str
}

func (s EchoService_echo_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoService_echo_Params) DecodeFromPtr(p capnp.Ptr) EchoService_echo_Params {
	return EchoService_echo_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoService_echo_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoService_echo_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoService_echo_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoService_echo_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoService_echo_Params) Req() (EchoRequest, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EchoRequest(p.Struct()), err
}

func (s EchoService_echo_Params) HasReq() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoService_echo_Params) SetReq(v EchoRequest) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewReq sets the req field to a newly
// allocated EchoRequest struct, preferring placement in s's segment.
func (s EchoService_echo_Params) NewReq() (EchoRequest, error) {
	ss, err := NewEchoRequest(capnp.Struct(s).Segment())
	if err != nil {
		return EchoRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// EchoService_echo_Params_List is a list of EchoService_echo_Params.
type EchoService_echo_Params_List = capnp.StructList[EchoService_echo_Params]

// NewEchoService_echo_Params creates a new list of EchoService_echo_Params.
func NewEchoService_echo_Params_List(s *capnp.Segment, sz int32) (EchoService_echo_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[EchoService_echo_Params](l), err
}

// EchoService_echo_Params_Future is a wrapper for a EchoService_echo_Params promised by a client call.
type EchoService_echo_Params_Future struct{ *capnp.Future }

func (f EchoService_echo_Params_Future) Struct() (EchoService_echo_Params, error) {
	p, err := f.Future.Ptr()
	return EchoService_echo_Params(p.Struct()), err
}
func (p EchoService_echo_Params_Future) Req() EchoRequest_Future {
	return EchoRequest_Future{Future: p.Future.Field(0, nil)}
}

type EchoService_echo_Results capnp.Struct

// EchoService_echo_Results_TypeID is the unique identifier for the type EchoService_echo_Results.
const EchoService_echo_Results_TypeID = 0xf47bc8e9b85ec174

func NewEchoService_echo_Results(s *capnp.Segment) (EchoService_echo_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Results(st), err
}

func NewRootEchoService_echo_Results(s *capnp.Segment) (EchoService_echo_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return EchoService_echo_Results(st), err
}

func ReadRootEchoService_echo_Results(msg *capnp.Message) (EchoService_echo_Results, error) {
	root, err := msg.Root()
	return EchoService_echo_Results(root.Struct()), err
}

func (s EchoService_echo_Results) String() string {
	str, _ := text.Marshal(0xf47bc8e9b85ec174, capnp.Struct(s))
	return str
}

func (s EchoService_echo_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoService_echo_Results) DecodeFromPtr(p capnp.Ptr) EchoService_echo_Results {
	return EchoService_echo_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoService_echo_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoService_echo_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoService_echo_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoService_echo_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoService_echo_Results) Resp() (EchoResponse, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return EchoResponse(p.Struct()), err
}

func (s EchoService_echo_Results) HasResp() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoService_echo_Results) SetResp(v EchoResponse) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResp sets the resp field to a newly
// allocated EchoResponse struct, preferring placement in s's segment.
func (s EchoService_echo_Results) NewResp() (EchoResponse, error) {
	ss, err := NewEchoResponse(capnp.Struct(s).Segment())
	if err != nil {
		return EchoResponse{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// EchoService_echo_Results_List is a list of EchoService_echo_Results.
type EchoService_echo_Results_List = capnp.StructList[EchoService_echo_Results]

// NewEchoService_echo_Results creates a new list of EchoService_echo_Results.
func NewEchoService_echo_Results_List(s *capnp.Segment, sz int32) (EchoService_echo_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[EchoService_echo_Results](l), err
}

// EchoService_echo_Results_Future is a wrapper for a EchoService_echo_Results promised by a client call.
type EchoService_echo_Results_Future struct{ *capnp.Future }

func (f EchoService_echo_Results_Future) Struct() (EchoService_echo_Results, error) {
	p, err := f.Future.Ptr()
	return EchoService_echo_Results(p.Struct()), err
}
func (p EchoService_echo_Results_Future) Resp() EchoResponse_Future {
	return EchoResponse_Future{Future: p.Future.Field(0, nil)}
}

type EchoRequest capnp.Struct

// EchoRequest_TypeID is the unique identifier for the type EchoRequest.
const EchoRequest_TypeID = 0xc1220377c3a1b7a0

func NewEchoRequest(s *capnp.Segment) (EchoRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoRequest(st), err
}

func NewRootEchoRequest(s *capnp.Segment) (EchoRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoRequest(st), err
}

func ReadRootEchoRequest(msg *capnp.Message) (EchoRequest, error) {
	root, err := msg.Root()
	return EchoRequest(root.Struct()), err
}

func (s EchoRequest) String() string {
	str, _ := text.Marshal(0xc1220377c3a1b7a0, capnp.Struct(s))
	return str
}

func (s EchoRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoRequest) DecodeFromPtr(p capnp.Ptr) EchoRequest {
	return EchoRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoRequest) Id() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s EchoRequest) SetId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s EchoRequest) Score() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s EchoRequest) SetScore(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s EchoRequest) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EchoRequest) HasUsername() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoRequest) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EchoRequest) SetUsername(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EchoRequest) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s EchoRequest) HasContent() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s EchoRequest) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s EchoRequest) SetContent(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// EchoRequest_List is a list of EchoRequest.
type EchoRequest_List = capnp.StructList[EchoRequest]

// NewEchoRequest creates a new list of EchoRequest.
func NewEchoRequest_List(s *capnp.Segment, sz int32) (EchoRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[EchoRequest](l), err
}

// EchoRequest_Future is a wrapper for a EchoRequest promised by a client call.
type EchoRequest_Future struct{ *capnp.Future }

func (f EchoRequest_Future) Struct() (EchoRequest, error) {
	p, err := f.Future.Ptr()
	return EchoRequest(p.Struct()), err
}

type EchoResponse capnp.Struct

// EchoResponse_TypeID is the unique identifier for the type EchoResponse.
const EchoResponse_TypeID = 0xb798c2c3642ab860

func NewEchoResponse(s *capnp.Segment) (EchoResponse, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoResponse(st), err
}

func NewRootEchoResponse(s *capnp.Segment) (EchoResponse, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return EchoResponse(st), err
}

func ReadRootEchoResponse(msg *capnp.Message) (EchoResponse, error) {
	root, err := msg.Root()
	return EchoResponse(root.Struct()), err
}

func (s EchoResponse) String() string {
	str, _ := text.Marshal(0xb798c2c3642ab860, capnp.Struct(s))
	return str
}

func (s EchoResponse) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (EchoResponse) DecodeFromPtr(p capnp.Ptr) EchoResponse {
	return EchoResponse(capnp.Struct{}.DecodeFromPtr(p))
}

func (s EchoResponse) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s EchoResponse) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s EchoResponse) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s EchoResponse) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s EchoResponse) Id() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s EchoResponse) SetId(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

func (s EchoResponse) Score() int32 {
	return int32(capnp.Struct(s).Uint32(4))
}

func (s EchoResponse) SetScore(v int32) {
	capnp.Struct(s).SetUint32(4, uint32(v))
}

func (s EchoResponse) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s EchoResponse) HasUsername() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s EchoResponse) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s EchoResponse) SetUsername(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s EchoResponse) Content() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s EchoResponse) HasContent() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s EchoResponse) ContentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s EchoResponse) SetContent(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// EchoResponse_List is a list of EchoResponse.
type EchoResponse_List = capnp.StructList[EchoResponse]

// NewEchoResponse creates a new list of EchoResponse.
func NewEchoResponse_List(s *capnp.Segment, sz int32) (EchoResponse_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[EchoResponse](l), err
}

// EchoResponse_Future is a wrapper for a EchoResponse promised by a client call.
type EchoResponse_Future struct{ *capnp.Future }

func (f EchoResponse_Future) Struct() (EchoResponse, error) {
	p, err := f.Future.Ptr()
	return EchoResponse(p.Struct()), err
}

const schema_bf5147bb3b06fa3d = "x\xda\xcc\x92Mk\x13Q\x14\x86\xdf\xf7\x9e\x99Fh" +
	"Cs\x9d\x80\xd0M!\x14\x84@\x8b\x1f\xb8Q4E" +
	"\x90\x82\xab\xdc\x94.\x0a*\x1d\xa6\x17\x12Hf\x92\xf9" +
	"\xf0\x03\x11\xf1_\xb8\xd4_\xd1R\x17\xd2v\xe3B\\" +
	"\xbbWPw.D\xd0\x85#\xd7\x9aD!\xe0\xd6\xdd" +
	"9\x87s\x1f\x9e\xc3}\xcf\x9d\xe5\xbaw\xbe\xba,P" +
	"f\xc5\x9f+w\xf6\x9b\xbb\xc7GO\xf7`\xe6\xc9\xf2" +
	"\xea\xf7\xb9+/6\xccK\xf8\xaa\x02\x04\x05\x8f\x82G" +
	"t\xd5\x03~\x00\xcbg{\xcf\x8f\xefI\xe3p\xe6\xb2" +
	"Q\x07\xc1\xf6\xafjK\xb9\xe57\xd7N\x0f\x8a\xaf\x9d" +
	"\xb7\xd0g\x08\xf8\x0esqU\x96\x08\x06\x97\xa4\x05\xfe" +
	"\xa8\xbe\x7f\xf7\xed\xf5\xe7\x8fz^\xa6(0\xd8\x92\x83" +
	"\xe0\xb68\xce\xb6l\x04O\\U\xe6\x87w\xf6?\xbd" +
	"z\xf8\xe5OVO\x1a\x8e5\x92\x16VK\x1bu\x93" +
	"\xb5(\x1c\xaaxx\xf9F\xd4M:6\x1b&qf" +
	"\xd1&MM<\xc0#\xa0\xc3%\xc0\xdc\x12\x9a\xae\xa2" +
	"&\xebtC{\x010;B\xd3W\xa4\xaaS\x01\xba" +
	"w\x130]\xa1\xc9\x15\xb5\xb0N\x01\xf4\xe8:`\xfa" +
	"Bs_Qz\xbb\xf4\xa0\xe8\x81\xcbY\x94\xa4v\xdc" +
	"\x95Ef\xd38\x1cX\x00\\\x80\xe2\x02\xf88J\xe2" +
	"\xdc\xc6\xf9\xb8\x9f\xe8r\xac\xdb\xb2\xa3\xc2f\xf9\xffm" +
	"+\xbfm7mz\xb7\x17\xd957_i\x87i(" +
	"\x83\xccx\x13\xedj\x030\xa7\x84\xa6\xaeXI\xed\x88" +
	"\xb5ip@\xd6f\xdc\xbf\xd9:A\xba\xfb=\xf1\x81" +
	"Iz8\xfez\xad\x9bP\xda\xaf,\xba\xb7\xebl\xf3" +
	"\x1f^\x1d\x9b\x15\x95~\xfe\x97Xs*\xb6\x98\xdal" +
	"\xc8\xda4\xff'f?\x03\x00\x00\xff\xff\xce\xcc\xbb8"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_bf5147bb3b06fa3d,
		Nodes: []uint64{
			0xb798c2c3642ab860,
			0xc1220377c3a1b7a0,
			0xd852f6756d123ece,
			0xe8f0ccf9e3e40d00,
			0xf47bc8e9b85ec174,
		},
		Compressed: true,
	})
}
