apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
          - /bin/sh
          - -c
          - |
            bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      containers:
      - name: frontend-kvstore-symphony
        image: appnetorg/kvstore-symphony:latest
        command: ["/app/frontend"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: LOG_LEVEL
          value: info
        - name: ENABLE_ENCRYPTION
          value: "false"
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command: ["/app/proxy"]
        securityContext:
          runAsUser: 1337
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: LOG_LEVEL
          value: info
        - name: ENABLE_PACKET_BUFFERING
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kvstore
  labels:
    app: kvstore
spec:
  clusterIP: None
  ports:
  - name: kvstore
    port: 11000
    protocol: UDP
    targetPort: 11000
  selector:
    app: kvstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvstore
  template:
    metadata:
      name: kvstore
      labels:
        app: kvstore
    spec:
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
          - /bin/sh
          - -c
          - |
            bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
      containers:
      - image: appnetorg/kvstore-symphony:latest
        name: kvstore-kvstore-symphony
        command: ["/app/kvstore"]
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: LOG_LEVEL
          value: info
        - name: ENABLE_ENCRYPTION
          value: "false"
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command: ["/app/proxy"]
        securityContext:
          runAsUser: 1337
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: LOG_LEVEL
          value: info
        - name: ENABLE_PACKET_BUFFERING
          value: "true"