// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: test.proto

package Test

import (
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. Fixed length scalar types
type Fixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FInt32        int32                  `protobuf:"varint,1,opt,name=f_int32,json=fInt32,proto3" json:"f_int32,omitempty"`
	FInt64        int64                  `protobuf:"varint,2,opt,name=f_int64,json=fInt64,proto3" json:"f_int64,omitempty"`
	FUint32       uint32                 `protobuf:"varint,3,opt,name=f_uint32,json=fUint32,proto3" json:"f_uint32,omitempty"`
	FUint64       uint64                 `protobuf:"varint,4,opt,name=f_uint64,json=fUint64,proto3" json:"f_uint64,omitempty"`
	FBool         bool                   `protobuf:"varint,5,opt,name=f_bool,json=fBool,proto3" json:"f_bool,omitempty"`
	FFloat        float32                `protobuf:"fixed32,6,opt,name=f_float,json=fFloat,proto3" json:"f_float,omitempty"`
	FDouble       float64                `protobuf:"fixed64,7,opt,name=f_double,json=fDouble,proto3" json:"f_double,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fixed) Reset() {
	*x = Fixed{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fixed) ProtoMessage() {}

func (x *Fixed) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fixed.ProtoReflect.Descriptor instead.
func (*Fixed) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Fixed) GetFInt32() int32 {
	if x != nil {
		return x.FInt32
	}
	return 0
}

func (x *Fixed) GetFInt64() int64 {
	if x != nil {
		return x.FInt64
	}
	return 0
}

func (x *Fixed) GetFUint32() uint32 {
	if x != nil {
		return x.FUint32
	}
	return 0
}

func (x *Fixed) GetFUint64() uint64 {
	if x != nil {
		return x.FUint64
	}
	return 0
}

func (x *Fixed) GetFBool() bool {
	if x != nil {
		return x.FBool
	}
	return false
}

func (x *Fixed) GetFFloat() float32 {
	if x != nil {
		return x.FFloat
	}
	return 0
}

func (x *Fixed) GetFDouble() float64 {
	if x != nil {
		return x.FDouble
	}
	return 0
}

// 2. Variable length scalar types
type Var struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VString       string                 `protobuf:"bytes,1,opt,name=v_string,json=vString,proto3" json:"v_string,omitempty"`
	VBytes        []byte                 `protobuf:"bytes,2,opt,name=v_bytes,json=vBytes,proto3" json:"v_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Var) Reset() {
	*x = Var{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Var) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Var) ProtoMessage() {}

func (x *Var) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Var.ProtoReflect.Descriptor instead.
func (*Var) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *Var) GetVString() string {
	if x != nil {
		return x.VString
	}
	return ""
}

func (x *Var) GetVBytes() []byte {
	if x != nil {
		return x.VBytes
	}
	return nil
}

// 3. Repeated fixed length types
type RepeatedFixed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RInt32        []int32                `protobuf:"varint,1,rep,packed,name=r_int32,json=rInt32,proto3" json:"r_int32,omitempty"`
	RInt64        []int64                `protobuf:"varint,2,rep,packed,name=r_int64,json=rInt64,proto3" json:"r_int64,omitempty"`
	RUint32       []uint32               `protobuf:"varint,3,rep,packed,name=r_uint32,json=rUint32,proto3" json:"r_uint32,omitempty"`
	RUint64       []uint64               `protobuf:"varint,4,rep,packed,name=r_uint64,json=rUint64,proto3" json:"r_uint64,omitempty"`
	RFloat        []float32              `protobuf:"fixed32,5,rep,packed,name=r_float,json=rFloat,proto3" json:"r_float,omitempty"`
	RDouble       []float64              `protobuf:"fixed64,6,rep,packed,name=r_double,json=rDouble,proto3" json:"r_double,omitempty"`
	RBool         []bool                 `protobuf:"varint,7,rep,packed,name=r_bool,json=rBool,proto3" json:"r_bool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedFixed) Reset() {
	*x = RepeatedFixed{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedFixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedFixed) ProtoMessage() {}

func (x *RepeatedFixed) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedFixed.ProtoReflect.Descriptor instead.
func (*RepeatedFixed) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedFixed) GetRInt32() []int32 {
	if x != nil {
		return x.RInt32
	}
	return nil
}

func (x *RepeatedFixed) GetRInt64() []int64 {
	if x != nil {
		return x.RInt64
	}
	return nil
}

func (x *RepeatedFixed) GetRUint32() []uint32 {
	if x != nil {
		return x.RUint32
	}
	return nil
}

func (x *RepeatedFixed) GetRUint64() []uint64 {
	if x != nil {
		return x.RUint64
	}
	return nil
}

func (x *RepeatedFixed) GetRFloat() []float32 {
	if x != nil {
		return x.RFloat
	}
	return nil
}

func (x *RepeatedFixed) GetRDouble() []float64 {
	if x != nil {
		return x.RDouble
	}
	return nil
}

func (x *RepeatedFixed) GetRBool() []bool {
	if x != nil {
		return x.RBool
	}
	return nil
}

// 4. Repeated variable length types
type RepeatedVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RString       []string               `protobuf:"bytes,1,rep,name=r_string,json=rString,proto3" json:"r_string,omitempty"`
	RBytes        [][]byte               `protobuf:"bytes,2,rep,name=r_bytes,json=rBytes,proto3" json:"r_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedVar) Reset() {
	*x = RepeatedVar{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedVar) ProtoMessage() {}

func (x *RepeatedVar) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedVar.ProtoReflect.Descriptor instead.
func (*RepeatedVar) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedVar) GetRString() []string {
	if x != nil {
		return x.RString
	}
	return nil
}

func (x *RepeatedVar) GetRBytes() [][]byte {
	if x != nil {
		return x.RBytes
	}
	return nil
}

// 5. Nested messages (Deep Nesting)
type Leaf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeafId        int32                  `protobuf:"varint,1,opt,name=leaf_id,json=leafId,proto3" json:"leaf_id,omitempty"`
	LeafVal       string                 `protobuf:"bytes,2,opt,name=leaf_val,json=leafVal,proto3" json:"leaf_val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaf) Reset() {
	*x = Leaf{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaf) ProtoMessage() {}

func (x *Leaf) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaf.ProtoReflect.Descriptor instead.
func (*Leaf) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *Leaf) GetLeafId() int32 {
	if x != nil {
		return x.LeafId
	}
	return 0
}

func (x *Leaf) GetLeafVal() string {
	if x != nil {
		return x.LeafVal
	}
	return ""
}

type Level2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaf          *Leaf                  `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level2) Reset() {
	*x = Level2{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level2) ProtoMessage() {}

func (x *Level2) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level2.ProtoReflect.Descriptor instead.
func (*Level2) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *Level2) GetLeaf() *Leaf {
	if x != nil {
		return x.Leaf
	}
	return nil
}

type Level1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L2            *Level2                `protobuf:"bytes,1,opt,name=l2,proto3" json:"l2,omitempty"`
	L1Data        string                 `protobuf:"bytes,2,opt,name=l1_data,json=l1Data,proto3" json:"l1_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Level1) Reset() {
	*x = Level1{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Level1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Level1) ProtoMessage() {}

func (x *Level1) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Level1.ProtoReflect.Descriptor instead.
func (*Level1) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *Level1) GetL2() *Level2 {
	if x != nil {
		return x.L2
	}
	return nil
}

func (x *Level1) GetL1Data() string {
	if x != nil {
		return x.L1Data
	}
	return ""
}

type Root struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	L1            *Level1                `protobuf:"bytes,1,opt,name=l1,proto3" json:"l1,omitempty"`
	RootId        int32                  `protobuf:"varint,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Root) Reset() {
	*x = Root{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Root) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Root) ProtoMessage() {}

func (x *Root) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Root.ProtoReflect.Descriptor instead.
func (*Root) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *Root) GetL1() *Level1 {
	if x != nil {
		return x.L1
	}
	return nil
}

func (x *Root) GetRootId() int32 {
	if x != nil {
		return x.RootId
	}
	return 0
}

// 6. Complex Mixed
type ComplexMixed struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FInt32         int32                  `protobuf:"varint,1,opt,name=f_int32,json=fInt32,proto3" json:"f_int32,omitempty"` // private
	VString        string                 `protobuf:"bytes,2,opt,name=v_string,json=vString,proto3" json:"v_string,omitempty"`
	RInt64         []int64                `protobuf:"varint,3,rep,packed,name=r_int64,json=rInt64,proto3" json:"r_int64,omitempty"` // private
	NestedLeaf     *Leaf                  `protobuf:"bytes,4,opt,name=nested_leaf,json=nestedLeaf,proto3" json:"nested_leaf,omitempty"`
	RString        []string               `protobuf:"bytes,5,rep,name=r_string,json=rString,proto3" json:"r_string,omitempty"` // private
	FBool          bool                   `protobuf:"varint,6,opt,name=f_bool,json=fBool,proto3" json:"f_bool,omitempty"`
	RepeatedNested []*Root                `protobuf:"bytes,7,rep,name=repeated_nested,json=repeatedNested,proto3" json:"repeated_nested,omitempty"` // private
	VBytes         []byte                 `protobuf:"bytes,8,opt,name=v_bytes,json=vBytes,proto3" json:"v_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComplexMixed) Reset() {
	*x = ComplexMixed{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexMixed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexMixed) ProtoMessage() {}

func (x *ComplexMixed) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexMixed.ProtoReflect.Descriptor instead.
func (*ComplexMixed) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *ComplexMixed) GetFInt32() int32 {
	if x != nil {
		return x.FInt32
	}
	return 0
}

func (x *ComplexMixed) GetVString() string {
	if x != nil {
		return x.VString
	}
	return ""
}

func (x *ComplexMixed) GetRInt64() []int64 {
	if x != nil {
		return x.RInt64
	}
	return nil
}

func (x *ComplexMixed) GetNestedLeaf() *Leaf {
	if x != nil {
		return x.NestedLeaf
	}
	return nil
}

func (x *ComplexMixed) GetRString() []string {
	if x != nil {
		return x.RString
	}
	return nil
}

func (x *ComplexMixed) GetFBool() bool {
	if x != nil {
		return x.FBool
	}
	return false
}

func (x *ComplexMixed) GetRepeatedNested() []*Root {
	if x != nil {
		return x.RepeatedNested
	}
	return nil
}

func (x *ComplexMixed) GetVBytes() []byte {
	if x != nil {
		return x.VBytes
	}
	return nil
}

// 7. Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

var file_test_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50001,
		Name:          "Test.is_public",
		Tag:           "varint,50001,opt,name=is_public",
		Filename:      "test.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// optional bool is_public = 50001;
	E_IsPublic = &file_test_proto_extTypes[0]
)

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x04Test\x1a google/protobuf/descriptor.proto\"\xd2\x01\n" +
	"\x05Fixed\x12\x1d\n" +
	"\af_int32\x18\x01 \x01(\x05B\x04\x88\xb5\x18\x01R\x06fInt32\x12\x17\n" +
	"\af_int64\x18\x02 \x01(\x03R\x06fInt64\x12\x1f\n" +
	"\bf_uint32\x18\x03 \x01(\rB\x04\x88\xb5\x18\x01R\afUint32\x12\x19\n" +
	"\bf_uint64\x18\x04 \x01(\x04R\afUint64\x12\x1b\n" +
	"\x06f_bool\x18\x05 \x01(\bB\x04\x88\xb5\x18\x01R\x05fBool\x12\x17\n" +
	"\af_float\x18\x06 \x01(\x02R\x06fFloat\x12\x1f\n" +
	"\bf_double\x18\a \x01(\x01B\x04\x88\xb5\x18\x01R\afDouble\"?\n" +
	"\x03Var\x12\x1f\n" +
	"\bv_string\x18\x01 \x01(\tB\x04\x88\xb5\x18\x01R\avString\x12\x17\n" +
	"\av_bytes\x18\x02 \x01(\fR\x06vBytes\"\xd4\x01\n" +
	"\rRepeatedFixed\x12\x17\n" +
	"\ar_int32\x18\x01 \x03(\x05R\x06rInt32\x12\x1d\n" +
	"\ar_int64\x18\x02 \x03(\x03B\x04\x88\xb5\x18\x01R\x06rInt64\x12\x19\n" +
	"\br_uint32\x18\x03 \x03(\rR\arUint32\x12\x1f\n" +
	"\br_uint64\x18\x04 \x03(\x04B\x04\x88\xb5\x18\x01R\arUint64\x12\x17\n" +
	"\ar_float\x18\x05 \x03(\x02R\x06rFloat\x12\x1f\n" +
	"\br_double\x18\x06 \x03(\x01B\x04\x88\xb5\x18\x01R\arDouble\x12\x15\n" +
	"\x06r_bool\x18\a \x03(\bR\x05rBool\"G\n" +
	"\vRepeatedVar\x12\x1f\n" +
	"\br_string\x18\x01 \x03(\tB\x04\x88\xb5\x18\x01R\arString\x12\x17\n" +
	"\ar_bytes\x18\x02 \x03(\fR\x06rBytes\"@\n" +
	"\x04Leaf\x12\x1d\n" +
	"\aleaf_id\x18\x01 \x01(\x05B\x04\x88\xb5\x18\x01R\x06leafId\x12\x19\n" +
	"\bleaf_val\x18\x02 \x01(\tR\aleafVal\".\n" +
	"\x06Level2\x12$\n" +
	"\x04leaf\x18\x01 \x01(\v2\n" +
	".Test.LeafB\x04\x88\xb5\x18\x01R\x04leaf\"E\n" +
	"\x06Level1\x12\x1c\n" +
	"\x02l2\x18\x01 \x01(\v2\f.Test.Level2R\x02l2\x12\x1d\n" +
	"\al1_data\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\x06l1Data\"C\n" +
	"\x04Root\x12\"\n" +
	"\x02l1\x18\x01 \x01(\v2\f.Test.Level1B\x04\x88\xb5\x18\x01R\x02l1\x12\x17\n" +
	"\aroot_id\x18\x02 \x01(\x05R\x06rootId\"\xa0\x02\n" +
	"\fComplexMixed\x12\x17\n" +
	"\af_int32\x18\x01 \x01(\x05R\x06fInt32\x12\x1f\n" +
	"\bv_string\x18\x02 \x01(\tB\x04\x88\xb5\x18\x01R\avString\x12\x17\n" +
	"\ar_int64\x18\x03 \x03(\x03R\x06rInt64\x121\n" +
	"\vnested_leaf\x18\x04 \x01(\v2\n" +
	".Test.LeafB\x04\x88\xb5\x18\x01R\n" +
	"nestedLeaf\x12\x19\n" +
	"\br_string\x18\x05 \x03(\tR\arString\x12\x1b\n" +
	"\x06f_bool\x18\x06 \x01(\bB\x04\x88\xb5\x18\x01R\x05fBool\x123\n" +
	"\x0frepeated_nested\x18\a \x03(\v2\n" +
	".Test.RootR\x0erepeatedNested\x12\x1d\n" +
	"\av_bytes\x18\b \x01(\fB\x04\x88\xb5\x18\x01R\x06vBytes\"\a\n" +
	"\x05Empty:<\n" +
	"\tis_public\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\bR\bisPublicB\bZ\x06./Testb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_test_proto_goTypes = []any{
	(*Fixed)(nil),                   // 0: Test.Fixed
	(*Var)(nil),                     // 1: Test.Var
	(*RepeatedFixed)(nil),           // 2: Test.RepeatedFixed
	(*RepeatedVar)(nil),             // 3: Test.RepeatedVar
	(*Leaf)(nil),                    // 4: Test.Leaf
	(*Level2)(nil),                  // 5: Test.Level2
	(*Level1)(nil),                  // 6: Test.Level1
	(*Root)(nil),                    // 7: Test.Root
	(*ComplexMixed)(nil),            // 8: Test.ComplexMixed
	(*Empty)(nil),                   // 9: Test.Empty
	(*descriptorpb.FieldOptions)(nil), // 10: google.protobuf.FieldOptions
}
var file_test_proto_depIdxs = []int32{
	4,  // 0: Test.Level2.leaf:type_name -> Test.Leaf
	5,  // 1: Test.Level1.l2:type_name -> Test.Level2
	6,  // 2: Test.Root.l1:type_name -> Test.Level1
	4,  // 3: Test.ComplexMixed.nested_leaf:type_name -> Test.Leaf
	7,  // 4: Test.ComplexMixed.repeated_nested:type_name -> Test.Root
	10, // 5: Test.is_public:extendee -> google.protobuf.FieldOptions
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	5,  // [5:6] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
		ExtensionInfos:    file_test_proto_extTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
