// Code generated by capnpc-go. DO NOT EDIT.

package capnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type Money capnp.Struct

// Money_TypeID is the unique identifier for the type Money.
const Money_TypeID = 0xa627db09bd09de37

func NewMoney(s *capnp.Segment) (Money, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Money(st), err
}

func NewRootMoney(s *capnp.Segment) (Money, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return Money(st), err
}

func ReadRootMoney(msg *capnp.Message) (Money, error) {
	root, err := msg.Root()
	return Money(root.Struct()), err
}

func (s Money) String() string {
	str, _ := text.Marshal(0xa627db09bd09de37, capnp.Struct(s))
	return str
}

func (s Money) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Money) DecodeFromPtr(p capnp.Ptr) Money {
	return Money(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Money) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Money) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Money) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Money) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Money) CurrencyCode() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Money) HasCurrencyCode() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Money) CurrencyCodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Money) SetCurrencyCode(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Money) Units() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Money) SetUnits(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Money) Nanos() int32 {
	return int32(capnp.Struct(s).Uint32(8))
}

func (s Money) SetNanos(v int32) {
	capnp.Struct(s).SetUint32(8, uint32(v))
}

// Money_List is a list of Money.
type Money_List = capnp.StructList[Money]

// NewMoney creates a new list of Money.
func NewMoney_List(s *capnp.Segment, sz int32) (Money_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[Money](l), err
}

// Money_Future is a wrapper for a Money promised by a client call.
type Money_Future struct{ *capnp.Future }

func (f Money_Future) Struct() (Money, error) {
	p, err := f.Future.Ptr()
	return Money(p.Struct()), err
}

type CurrencyConversionRequest capnp.Struct

// CurrencyConversionRequest_TypeID is the unique identifier for the type CurrencyConversionRequest.
const CurrencyConversionRequest_TypeID = 0xbda65cba06d3de8f

func NewCurrencyConversionRequest(s *capnp.Segment) (CurrencyConversionRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return CurrencyConversionRequest(st), err
}

func NewRootCurrencyConversionRequest(s *capnp.Segment) (CurrencyConversionRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return CurrencyConversionRequest(st), err
}

func ReadRootCurrencyConversionRequest(msg *capnp.Message) (CurrencyConversionRequest, error) {
	root, err := msg.Root()
	return CurrencyConversionRequest(root.Struct()), err
}

func (s CurrencyConversionRequest) String() string {
	str, _ := text.Marshal(0xbda65cba06d3de8f, capnp.Struct(s))
	return str
}

func (s CurrencyConversionRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CurrencyConversionRequest) DecodeFromPtr(p capnp.Ptr) CurrencyConversionRequest {
	return CurrencyConversionRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CurrencyConversionRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CurrencyConversionRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CurrencyConversionRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CurrencyConversionRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CurrencyConversionRequest) From() (Money, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Money(p.Struct()), err
}

func (s CurrencyConversionRequest) HasFrom() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CurrencyConversionRequest) SetFrom(v Money) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewFrom sets the from field to a newly
// allocated Money struct, preferring placement in s's segment.
func (s CurrencyConversionRequest) NewFrom() (Money, error) {
	ss, err := NewMoney(capnp.Struct(s).Segment())
	if err != nil {
		return Money{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s CurrencyConversionRequest) ToCode() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CurrencyConversionRequest) HasToCode() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CurrencyConversionRequest) ToCodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CurrencyConversionRequest) SetToCode(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s CurrencyConversionRequest) UserId() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s CurrencyConversionRequest) HasUserId() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CurrencyConversionRequest) UserIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s CurrencyConversionRequest) SetUserId(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// CurrencyConversionRequest_List is a list of CurrencyConversionRequest.
type CurrencyConversionRequest_List = capnp.StructList[CurrencyConversionRequest]

// NewCurrencyConversionRequest creates a new list of CurrencyConversionRequest.
func NewCurrencyConversionRequest_List(s *capnp.Segment, sz int32) (CurrencyConversionRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[CurrencyConversionRequest](l), err
}

// CurrencyConversionRequest_Future is a wrapper for a CurrencyConversionRequest promised by a client call.
type CurrencyConversionRequest_Future struct{ *capnp.Future }

func (f CurrencyConversionRequest_Future) Struct() (CurrencyConversionRequest, error) {
	p, err := f.Future.Ptr()
	return CurrencyConversionRequest(p.Struct()), err
}
func (p CurrencyConversionRequest_Future) From() Money_Future {
	return Money_Future{Future: p.Future.Field(0, nil)}
}

const schema_8c0c0c0c0c0c0c0c = "x\xda\\\xd0AK:A\x18\x06\xf0\xe7\x99\xd9U\x84" +
	"\xfd\xa3\x83\xc2\xbf\x9b\xc7 (\xc8\x0e\x81\x17\x05\x0b\x12" +
	"\x14\x9c\xe8\xd0\xa1\x8b\xe8\x04\x06\xce\xd8\xae\x1b\xf8\x1d\x82" +
	"\xa8{\x87.^\xbd\x07~\x8a\x8e\x81\xdf\xa1C\x87N" +
	"\x1bK\xe9Js\x19\xde\x87\xf7\x81\x1foi\xd1\xf4\x0e" +
	"\xff\xfd\x17\x10z\xc7\xcf%\xc7\xab\xc2\xb2\xf0\xbe;\x87" +
	"\x0e(\x92\xe0\xe7\xdd\xc3g\x1eP\x1fO\xea+\xfd?" +
	"\x17`\xf2\xb0z\xcb\xbd^\xcd\x97P\x01\xb7\x16e\x1e" +
	"8zd\x8d\xe5\x97\xb4S~\xe6\x02\xfb\xc9\xd8Y3" +
	";\x18\xf49\xb1\x93z\xd7Y\xc3Y\x8f\xd4\x81\xf4\x00" +
	"\x8f\x80:\xbd\x01\xf4\x89\xa4\xee\x09\x92\x15\xa6Y\xb7\x06" +
	"\xe83I}!\xa8\x84\xa8P\x00J\xa7aGR_" +
	"\x0a&\x838\x0c\x8d\x1d\xccPl\xb9\xa1a\x00\xc1\x00" +
	"\xac\xc6v4\x8d\xe8C\xd0\x07\xab\xb6o]D\x0f\x82" +
	"\x1e\xb8\x91\xc8T\xd2\xfa\xed\xb7\x9c\xbd3a4r\xf6" +
	"\xdcToc\x13M\xff\xe8\xf6\x00\xdd\x94\xd4\x1dA\xb5" +
	"\xe6\xb5\xeb\x19y\xc3\xeb\xd63s\xf1:tc\x96\xb2" +
	"\x9b\x82,\x81\x8d\xa9\xdb\xd66\xe2\xc8\x84\xed\xe1z\xfc" +
	"\x0e\x00\x00\xff\xff\xf0\x99S\xac"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_8c0c0c0c0c0c0c0c,
		Nodes: []uint64{
			0xa627db09bd09de37,
			0xbda65cba06d3de8f,
		},
		Compressed: true,
	})
}
