#!/bin/bash

echo "Applying Symphony iptables rules..."

iptables-restore <<EOF
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -p udp -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A PREROUTING -p udp -m udp --dport 10000:65535 -j CONNMARK --set-xmark 0x2/0xffffffff
-A PREROUTING -p udp -j CONNMARK --restore-mark --nfmask 0xffffffff --ctmask 0xffffffff
-A OUTPUT -p udp -m udp --dport 10000:65535 -j CONNMARK --set-xmark 0x1/0xffffffff
COMMIT
# Completed on Wed Jul 30 00:27:55 2025
# Generated by iptables-save v1.8.7 on Wed Jul 30 00:27:55 2025
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -p udp -m connmark --mark 0x1 -j REDIRECT --to-ports 15002
-A PREROUTING -p udp -m connmark --mark 0x2 -j REDIRECT --to-ports 15006
-A OUTPUT -p udp -m udp --dport 10000:65535 -m owner ! --uid-owner proxyuser -j REDIRECT --to-ports 15002
-A OUTPUT -p udp -m connmark --mark 0x2 -m owner ! --uid-owner proxyuser -j REDIRECT --to-ports 15006
COMMIT
EOF

echo "iptables rules applied successfully for symphony proxy."
