package main

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

func generateFile(plugin *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_aprc.pb.go"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-aprc. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import (`)
	g.P(`  "context"`)
	g.P(`  "github.com/appnet-org/aprc/pkg/rpc"`)
	g.P(`)`)
	g.P()

	for _, service := range file.Services {
		genService(g, service)
	}
}

func genService(g *protogen.GeneratedFile, service *protogen.Service) {
	svcName := service.GoName
	clientName := svcName + "Client"

	// === Client interface ===
	g.P("// ", clientName, " is the client API for ", svcName, " service.")
	g.P("type ", clientName, " interface {")
	for _, m := range service.Methods {
		g.P(m.GoName, "(ctx context.Context, req *", m.Input.GoIdent, ") (*", m.Output.GoIdent, ", error)")
	}
	g.P("}")
	g.P()

	// === Client implementation ===
	implName := "aprc" + clientName
	g.P("type ", implName, " struct {")
	g.P("  client *rpc.Client")
	g.P("}")
	g.P()

	g.P("func New", clientName, "(client *rpc.Client) ", clientName, " {")
	g.P("  return &", implName, "{client: client}")
	g.P("}")
	g.P()

	for _, m := range service.Methods {
		serviceName := service.GoName
		methodName := m.GoName

		g.P("func (c *", implName, ") ", methodName,
			"(ctx context.Context, req *", m.Input.GoIdent, ") (*", m.Output.GoIdent, ", error) {")

		g.P("  resp := new(", m.Output.GoIdent, ")")
		g.P("  if err := c.client.Call(\"", serviceName, "\", \"", methodName, "\", req, resp); err != nil {")
		g.P("    return nil, err")
		g.P("  }")
		g.P("  return resp, nil")
		g.P("}")
		g.P()
	}

	// === Server interface ===
	g.P("type ", svcName, "Server interface {")
	for _, m := range service.Methods {
		g.P(m.GoName, "(ctx context.Context, req *", m.Input.GoIdent, ") (*", m.Output.GoIdent, ", error)")
	}
	g.P("}")
	g.P()

	// === Register<Service>Server ===
	g.P("func Register", svcName, "Server(s *rpc.Server, srv ", svcName, "Server) {")
	g.P("  s.RegisterService(&rpc.ServiceDesc{")
	g.P("    ServiceName: \"", service.GoName, "\",")
	g.P("    ServiceImpl: srv,")
	g.P("    Methods: map[string]*rpc.MethodDesc{")
	for _, m := range service.Methods {
		handlerName := fmt.Sprintf("_%s_%s_Handler", svcName, m.GoName)
		g.P("      \"", m.GoName, "\": {")
		g.P("        MethodName: \"", m.GoName, "\",")
		g.P("        Handler: ", handlerName, ",")
		g.P("      },")
	}
	g.P("    },")
	g.P("  }, srv)")
	g.P("}")

	// === Handler Implementations ===
	for _, m := range service.Methods {
		handlerName := fmt.Sprintf("_%s_%s_Handler", svcName, m.GoName)
		inputType := m.Input.GoIdent.GoName

		g.P("func ", handlerName, "(srv any, ctx context.Context, dec func(any) error) (any, error) {")
		g.P("  in := new(", inputType, ")")
		g.P("  if err := dec(in); err != nil { return nil, err }")
		g.P("  return srv.(", svcName, "Server).", m.GoName, "(ctx, in)")
		g.P("}")
		g.P()
	}
}
